/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qorffinqonewjiwouofi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvcmZmaW5xb25ld2ppd291b2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTI0MjIsImV4cCI6MjA3MzkyODQyMn0.hSfovyeV-fbm-bv7ikW8nsMU3wyfXZm028uEWUHhfBI"